### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Cyebukayire**
Fixed grammatical errors

### CODE REVIEW

**Review by NS007-dev — APPROVED** [review]
Thank you so much @Cyebukayire  I did not see these here! I will send you an invite to the org

**Comment by NS007-dev** [comment]
@all-contributors please add @Cyebukayire for content

**Comment by NS007-dev** [comment]
@Cyebukayire  You have received an email to join, or press this link - https://github.com/App-Choreography - , and you'll see a banner, for you to join the organisation! 🎉 

You can also show that you are part of this org, by making yourself public. This will show our profile org on your profile:
## Follow This:
1. After you join the organisation, search your name in the list of people. 🔍 
2.  Follow this below: ⬇️ 
image

**Comment by Cyebukayire** [comment]
alright, Thank you so much:)
I've done that

**Pull request merged**
